dist: bionic
language: go

go:
  - 1.x

git:
  depth: 2

env:
  global:
    - GO111MODULE=on
    - PATH=bin:$PATH
    - DOCKER_USERNAME=pix4d
    - COGITO_TEST_REPO_OWNER=pix4d
    - COGITO_TEST_REPO_NAME=cogito-test-read-write
    - COGITO_TEST_COMMIT_SHA=32e4b4f91bb8de500f6a7aa2011f93c3f322381c
    - COGITO_TEST_READ_ONLY_REPO_NAME=cogito-test-read-only
    - COGITO_TEST_READ_ONLY_COMMIT_SHA=a792bdb993c1caba10f94e051085b5183b1c674b
    # secure contains the following keys:
    # COGITO_TEST_OAUTH_TOKEN=
    - secure: "r4N4fmCd9OePpjVhqK8I/3IP0iMpytad6amt30tqB/LSdahY+q3CUhYDOBj2EhIQBSIrw9MqFf2qo2kAKazjSnB6LVhq3mYbTKOveM7AcI9ZB7ZcchZ8sQ63kGr0be2739Y8z4lU/H2k14G1f8wR2bqMPK01zxkeXGrQdndZrzacMWqwjzcy0wG7Cod6vCa9GBx48XibaysAJ2Si3DOLc+xncEjbjF4L72i0RXE9qH5H/febet1xzHMScXRV/D0PEz7z5I2YCspzxLtBByc2LOeZj/0oic9qYdTZyEb1PAB5jtNdrZICK4tiXw9wWkmpNr6thddfEHmtMvbD08nD3M51SCkbhmHrbqq6rt12U6TPkQbOL/KuTCyhGJW3WxTaX++a4O6TFfr0pCgpx1RZ0PnY3qDEaBRGxDFya4/pPVK8KJd3un0Y++rGWNK1Yc3Ib2IoyzKohKUnFS5PIitZiEgvonNng3oytzMIP1KikSv/oUJkLtpmSez2TN52EH4ELNzZNPkviJy2d+btkTK11WiQ+x1ZqkbRnYDeIpZZNITe+xvoy96VuqqZz9s3PUXC8nn9u48uBq0M+Ga/clEdcxlnvLS7hC1hyPQ+FGnDPzgwnJGf1sRgC7yehowPJMuQ4cs0mOdo0dTPhP2cSYtvUXTXQYnl71lxIx8Lrh9fx+0="

services:
  - docker

install:
  - curl --silent --location https://taskfile.dev/install.sh | sh
  - which task
  - task --version

script:
  # This is to fail fast, see https://github.com/travis-ci/travis-ci/issues/1066
  # :-(
  - task test || exit 1
  # - task docker-build || exit 1
  # - task docker-smoke || exit 1
  # - task docker-push || exit 1
