# Install `task` from https://taskfile.dev
# Run `task --list` to start.

version: "2.6"
expansions: 3

vars:
  TAG: '{{if env "TAG"}}{{env "TAG"}}{{else}}latest{{end}}'
  DOCKER_REGISTRY: docker.ci.pix4d.com/cogito:{{.TAG}}
  DATE: '{{ now | date "2006-01-02" }}'
  COMMIT:
    sh: git log -n 1 --format=%h
  REPO: github.com/Pix4D/cogito
  BUILD_INFO: "Tag: {{.TAG}}, commit: {{.COMMIT}}, date: {{.DATE}}"
  LDFLAGS: -w -X '{{.REPO}}/resource.buildinfo={{.BUILD_INFO}}'

tasks:
  default:
    deps: [test]
    desc: Sensible defaults if you invoke `task` without arguments.
  test:
    desc: Run the tests.
    cmds:
      # `-count 1` is the idiomatic way to always run the tests (do not use the test cache)
      - go test -count 1 ./...
  dotcopy:
    dir: bin
    cmds:
      - go build -ldflags "{{.LDFLAGS}}" ../cmd/dotcopy
  build-local:
    deps: [dotcopy]
    desc: Build on the local machine.
    dir: bin
    cmds:
      - go build -ldflags "{{.LDFLAGS}}" ../cmd/check
      - go build -ldflags "{{.LDFLAGS}}" ../cmd/in
      - go build -ldflags "{{.LDFLAGS}}" ../cmd/out
      - go build -ldflags "{{.LDFLAGS}}" ../cmd/hello
  build:
    desc: Build the Docker image. Use the TAG environment variable if set.
    cmds:
      - docker build --build-arg BUILD_INFO -t {{.DOCKER_REGISTRY}} .
    env:
      BUILD_INFO: "{{.BUILD_INFO}}"
  publish:
    deps: [build]
    desc: Publish the Docker image.
    cmds:
      - docker push {{.DOCKER_REGISTRY}}
