meta:

  gh-status_handlers: &gh-status-handlers
    on_success:
      put: gh-status
      inputs: [repo.git]
      params: {state: success}
    on_failure:
      put: gh-status
      inputs: [repo.git]
      params: {state: failure}
    on_error:
      put: gh-status
      inputs: [repo.git]
      params: {state: error}

  task-config: &task-config
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: alpine }
      run:
        path: /bin/sh
        args:
          - -c
          - |
            set -o errexit
            set -x
            echo "How many? Like the stars."
            exit 0


resource_types:

- name: cogito
  type: registry-image
  check_every: 24h
  source:
    repository: ((docker-registry))/cogito
    tag: ((tag))
    # Credentials needed only if private registry
    username: ((docker-username))
    password: ((docker-password))

resources:

- name: gh-status
  type: cogito
  # Since check is a no-op, we check infrequently to reduce load on the system.
  check_every: 24h
  source:
    # Optional, for debugging only.
    # log_level: debug
    # log_url: ((concourse_cognito_logs))
    owner: ((github-owner))
    repo: ((repo-name))
    access_token: ((oauth-personal-access-token))

- name: repo.git
  type: git
  source:
    uri: git@github.com:((github-owner))/((repo-name)).git
    branch: ((branch))
    # Private key is needed only for SSH access
    private_key: ((ssh-key))

jobs:

  - name: autocat
    <<: *gh-status-handlers
    plan:
      - get: repo.git
        trigger: true
      - put: gh-status
        inputs: [repo.git]
        params: {state: pending}
      - task: maybe-fail
        <<: *task-config

  - name: motormouse
    <<: *gh-status-handlers
    plan:
      - get: repo.git
        trigger: true
      - put: gh-status
        inputs: [repo.git]
        params: {state: pending}
      - task: maybe-fail
        <<: *task-config
